### ISSUE TITLE
How do you make a mobile app? 

### ISSUE THREAD

**Issue by amazinigmech2418** [heb12/heb12-android#3]
I could help if I knew how...

**Comment by Pufflegamerz** [comment]
Android Studio

**Comment by amazinigmech2418** [comment]
What is that?

**Comment by Pufflegamerz** [comment]
It's a software where you can create android apps. You code the apps in Java.

**Comment by amazinigmech2418** [comment]
OK. I don't know Java. I just know it always needs updates and is made by the people who made JS.

**Comment by MasterOfTheTiger** [comment]
No it is not made by the same people. The same company owns both copyrights though (Oracle)

**Comment by MasterOfTheTiger** [comment]
Java is another programming language that can be hard to learn. Java the program is for running Java programs.

**Comment by MasterOfTheTiger** [comment]
@herronjo I know, but they do not support GNU/Linux and it does not seem to be open source.

**Comment by MasterOfTheTiger** [comment]
@herronjo Also, it won't work without Node.js, and I think the program would be better in general if it was separate.
