### ISSUE TITLE
Ready start working on this

### ISSUE THREAD

**Issue by pufflegamerz** [heb12/heb12-android#5]
Finally got my cast off. I'm gonna start working on it again. Also, has this project been discontinued/paused?

**Comment by MasterOfTheTiger** [comment]
This has been paused because I am unable to work on anything for a while.

**Comment by Pufflegamerz** [comment]
ok

**Comment by MasterOfTheTiger** [comment]
Please work on it if you can though.

**Comment by MasterOfTheTiger** [comment]
Do you have a Discord account?

**Comment by MasterOfTheTiger** [comment]
We have both an Heb12 gitter and discord. What would work better? I would prefer Gitter, but we all have to check it.

**Comment by PetabyteStudios** [comment]
I have never really used any of those before. I'd be happy to communicate just through Github.

**Comment by MasterOfTheTiger** [comment]
Gitter is very easy to set up. It is integrated with GitHub pretty well. See this: https://gitter.im/heb12

**Comment by MasterOfTheTiger** [comment]
It may be easier for you to use it. But I am sure you can just use the Android SDK and a text editor.
