### ISSUE TITLE
God bless you :)

### ISSUE THREAD

**Issue by hotlittlewhitedog** [heb12/heb12-android#6]
Yop Guys, 

I found your app on snapcraft, I'm a developer too. 
Already created 2 bible apps (Android and Terminal), watch on Gitlab. 
Maybe we can share some stuffs... I'm under GPL3 also. 
Looking your issues, I see that you referenced my code ^^
https://github.com/heb12/heb12-android/issues/2

++

**Comment by MasterOfTheTiger** [comment]
Awesome. We have had some trouble with snapcraft (try installing our app). 

We can share stuff. I think I will view a lot of your Android app code.

**Comment by hotlittlewhitedog** [comment]
Ok good news.

An Android app takes long time to develop.

I was interested by snapcraft, what was the problem with your installation?

**Comment by MasterOfTheTiger** [comment]
It simply will not install when you run the command: sudo snap install heb12 --edge

**Comment by MasterOfTheTiger** [comment]
Well, I can get it to install. But it will not run when you install it. There are no desktop icons placed anywhere.

**Comment by hotlittlewhitedog** [comment]
Entry point problem...

**Comment by MasterOfTheTiger** [comment]
Do you have a solution?

**Comment by hotlittlewhitedog** [comment]
I don't know snapcraft, but there is always an entry point :smile:

**Comment by MasterOfTheTiger** [comment]
If you don't mind, could you check out this issue: https://github.com/heb12/heb12-desktop/issues/31
